### ISSUE TITLE
Webforms Claims

### ISSUE THREAD

**Issue by abomadi** [MacLeanElectrical/identityserver-contrib-membership#3]
Many thanks for this contribution, it's simply amazing for old asp.net client, however if you can provide some help on how to use this exactly with IS4

I have managed to run this project with IS4, and logged in successful now i want to make my .Net 4.5.1 App login via IS4 and authenticate the user, i did authenticate the user but without any information about him that should be come from DB (Memebership), any simple idea how to do this.

Again many thanks for this project

**Comment by stuartbfs** [comment]
Hi there,  thanks for the feedback - I wasn't sure if anyone was still using the asp.net Membership to warrant it!  

Can I check what information you are looking for to be returned?

**Comment by abomadi** [comment]
Unfortunately we are still using Membership because one of our CMS platform is using it. 
This is exactly what we want to do.
- User Access CMS Login which will ask IS4 to show it's login screen
- After authenticating on IS4 OWIN middleware will receive the response cookie using OpenIDConnect
- (here we have some missing information) to map the is4 principal to our showing the user as signed in so what we want exactly is user profile information, userid, email ...

**Comment by stuartbfs** [comment]
If you are requesting the "openid" and "email" claims, the userid and the e-mail address should in the Claims Identity on the client side following authentication.  

For the user profile information, is that from the aspnet_Profile table?

**Comment by abomadi** [comment]
Profile from asp_net and extended one, but im not sure where should i call the other table 
this is the middleware on the webforms 
```
 app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationType = "Cookies",
            });
            JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
           {
               AuthenticationType = "oidc",
               SignInAsAuthenticationType = "Cookies",
               Authority = "http://10.10.1.152:5000/",
               ClientId = "fitnessyard",
               RedirectUri = "http://localhost/",
               PostLogoutRedirectUri = "http://localhost/",
               ResponseType = "id_token",
               Scope = "openid profile email",
               UseTokenLifetime = false,
               Notifications = new OpenIdConnectAuthenticationNotifications
               {
                   SecurityTokenValidated = async n =>
                   {
                       var claims_to_exclude = new[]
                        {
                            "aud", "iss", "nbf", "exp", "nonce", "iat", "at_hash"
                        };

                       var claims_to_keep =
                           n.AuthenticationTicket.Identity.Claims
                           .Where(x => false == claims_to_exclude.Contains(x.Type)).ToList();
                       claims_to_keep.Add(new Claim("id_token", n.ProtocolMessage.IdToken));

                       if (n.ProtocolMessage.AccessToken != null)
                       {
                           claims_to_keep.Add(new Claim("access_token", n.ProtocolMessage.AccessToken));

                           var userInfoClient = new UserInfoClient(new Uri("http://10.10.1.152:5000/connect/userinfo"), n.ProtocolMessage.AccessToken);
                           var userInfoResponse = await userInfoClient.GetAsync();
                           var userInfoClaims = userInfoResponse.Claims
                               .Where(x => x.Item1 != "sub") // filter sub since we're already getting it from id_token
                               .Select(x => new Claim(x.Item1, x.Item2));
                           claims_to_keep.AddRange(userInfoClaims);
                       }

                       var ci = new ClaimsIdentity(
                           n.AuthenticationTicket.Identity.AuthenticationType,
                           "name", "role");
                       ci.AddClaims(claims_to_keep);

                       n.AuthenticationTicket = new Microsoft.Owin.Security.AuthenticationTicket(
                           ci, n.AuthenticationTicket.Properties
                       );
                   },
                   RedirectToIdentityProvider = n =>
                   {
                       if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                       {
                           var id_token = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
                           n.ProtocolMessage.IdTokenHint = id_token;
                       }

                       return Task.FromResult(0);
                   }
               }
           });
```

**Comment by stuartbfs** [comment]
I'll update the plugin to handle the profile data.  I'll also add in an action that can be passed into the plugin that will allow you to handle additional (extended data).  I'll aim to get this done relatively quickly.

**Comment by stuartbfs** [comment]
In the meantime, you could override the GetClaimsFromAccount method in MembershipClaimsService.cs from the plugin.

```csharp
public class ExtendedMembershipClaimsService : MembershipClaimsService
{
   public ExtendedMembershipClaimsService(
      IMembershipService membershipService,
      IRoleService roleService,
      IMembershipProfileService profileService,
      MembershipOptions options)
      : base(membershipService, roleService, profileService, options)
   {
   }


   public Task<IEnumerable<Claim>> GetClaimsFromAccount(MembershipUser user)
   {
      var claims = base.GetClaimsFromAccount(user).ToList();

      // Add additional claims here
      

      return claims;
   }

}
```

You should then be able to replace the existing MembershipClaimsService in the IdentityServer IOC container in the IdentityServer startup class.
```csharp
   services.AddIdentityServer()
               ...
               .AddMembershipService(new MembershipOptions
                {
                        ConnectionString = "......",
                        ApplicationName = "......" 
                })
                .Services.AddTransient<IMembershipClaimsService,ExtendedMembershipClaimsService>();

```

**Comment by abomadi** [comment]
Excellent, thanks for your efforts again, if you have some free time can you show an clear example how OWIN in webforms integrates with IS4 bringing the claims in Startup as i couldn't find any useful information online except the one i have showed it to you previously.

**Comment by stuartbfs** [comment]
You would need to look at the IdentityServer documentation / sample projects for webforms integration examples.  

This plugin is specifically for the IdentityServer instance and we don't have any active webform projects that we can source.
